---
# Set common settings like NTP, Hostname, Timezone

- name: Change cumulus user creds
  user:
    name: cumulus
    password: "{{ cumulus_pass }}"
    update_password: always

- import_tasks: time.yml
  tags:
    - time

- import_tasks: locale.yml
  tags:
    - locale

- import_tasks: motd.yml
  tags:
    - motd

- import_tasks: hostname.yml
  tags:
    - hostname

- import_tasks: dns.yml
  tags:
    - dns

- import_tasks: ssh.yml
  tags:
    - ssh
