---
- name: apply hostname
  command: hostname -F /etc/hostname

- name: apply timezone
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: restart ntp
  service:
    name: ntp@mgmt
    state: restarted

- name: rebuild locales database
  command: "en_US.UTF-8"
  with_items:
    - sudo dpkg-reconfigure locales -f noninteractive
    - sudo /usr/sbin/locale-gen
