---
- name: apply hostname
  command: hostname -F /etc/hostname

- name: apply timezone
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

#- name: restart ntp
#  service:
#    name: ntp@mgmt
#    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: rebuild locales database
  command: /usr/sbin/dpkg-reconfigure locales -f noninteractive
